name: docker build ci

on:
  push:
    tags:
      - 'v*'

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: d556f8
          password: ${{ secrets.GH_ACCESS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/esgforumwebsitedev/esgforum-react:latest
            ghcr.io/esgforumwebsitedev/esgforum-react:${{ env.RELEASE_VERSION }}
          ache-from: type=gha # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
          cache-to: type=gha,mode=max
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }} # pem 키--
          # 도커 작업
          script: |
            docker stop esg-web-react
            cd ~/app
            docker compose-up -d
